name: Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - "*"

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Test Coverage
        run: make test-cover